### ISSUE TITLE
modpython throws an AttributeError when trying to read web request headers

### ISSUE THREAD

**Issue by prawnsalad** [znc/znc#1225]
Python module snippet:
~~~python
	def OnWebPreRequest(self, WebSock, sPageName):
		http_headers = WebSock.m_msHeaders
~~~

First line of that function causes this traceback:
~~~
modpython: <no user>/httpadmin/OnWebPreRequest failed: Traceback (most recent call last):
  File "/home/darren/.znc/modules/httpadmin.py", line 91, in OnWebPreRequest
    http_headers = WebSock.m_msHeaders
  File "/usr/lib/znc/modpython/znc_core.py", line 6569, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, CWebSock, name)
  File "/usr/lib/znc/modpython/znc_core.py", line 74, in _swig_getattr
    return _swig_getattr_nondynamic(self, class_type, name, 0)
  File "/usr/lib/znc/modpython/znc_core.py", line 69, in _swig_getattr_nondynamic
    return object.__getattr__(self, name)
AttributeError: type object 'object' has no attribute '__getattr__'
~~~

**Comment by Liamraystanley** [comment]
I'm seeing the same issue on my end. Code to replicate the issue:

```python
class api(znc.Module):
    def OnWebPreRequest(self, WebSock, sPageName):
        users = dict(znc.CZNC.Get().GetUserMap())

        for name in users:
            # blockuser module
            mod_blockuser = znc.CZNC.Get().GetModules().FindModule('blockuser')

            if mod_blockuser:
                if mod_blockuser.HasNV(users[name].GetUserName()):
                    # ....
        # ....
```

Here is the exception from the original script, but alas the same issue it looks like:

```
Traceback (most recent call last):
  File "/home/znc/.znc/modules/api.py", line 98, in OnWebPreRequest
    if mod_blockuser.HasNV(users[name].GetUserName()):
  File "/home/znc/znc/modules/modpython/znc_core.py", line 3689, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, CModule, name)
  File "/home/znc/znc/modules/modpython/znc_core.py", line 74, in _swig_getattr
    return _swig_getattr_nondynamic(self, class_type, name, 0)
  File "/home/znc/znc/modules/modpython/znc_core.py", line 69, in _swig_getattr_nondynamic
    return object.__getattr__(self, name)
AttributeError: type object 'object' has no attribute '__getattr__'
```

**Comment by Liamraystanley** [comment]
Looks like my issue may not be 100% related. I was able to track down that it looks like `CModule::HasNV` was removed sometime before and/or up to 1.6.3, and now `CModule::ExistsNV` has taken it's place. I am not seeing that the documentation on this matter has been properly updated, as I had to scramble through the c++ source to find it.

Still not quite sure if it's related, but...
