### ISSUE TITLE
Crash in 1.6.5 when connecting to networks

### ISSUE THREAD

**Issue by MuffinMedic** [znc/znc#1384]
After starting ZNC up, while connecting to the networks, the following error was received and ZNC crashed.

```
/usr/include/c++/5/debug/safe_iterator.h:331:error: attempt to increment a
    singular iterator.
 
Objects involved in the operation:
iterator "this" @ 0x0x7ffd21bba230 {
type = N11__gnu_debug14_Safe_iteratorIN9__gnu_cxx17__normal_iteratorIPKP6CQueryNSt9__cxx19986vectorIS4_SaIS4_EEEEENSt7__debug6vectorIS4_S9_EEEE (constant iterator);
  state = singular;
  references sequence with type `NSt7__debug6vectorIP6CQuerySaIS2_EEE' @ 0x0x14c8680
}
fish: “znc -D” terminated by signal SIGABRT (Abort)
```

**Comment by DarthGandalf** [comment]
http://wiki.znc.in/Debugging

**Comment by MuffinMedic** [comment]
This is the output I got from `gdb`:

```
[2017-03-13 12:48:11.355111] (evan/snoonet) ZNC -> CLI [:irc.znc.in 305 MuffinMedic :You are no longer marked as being away]
/usr/include/c++/5/debug/safe_iterator.h:331:error: attempt to increment a 
    singular iterator.

Objects involved in the operation:
iterator "this" @ 0x0x7fffffffa680 {
type = N11__gnu_debug14_Safe_iteratorIN9__gnu_cxx17__normal_iteratorIPKP6CQueryNSt9__cxx19986vectorIS4_SaIS4_EEEEENSt7__debug6vectorIS4_S9_EEEE (constant iterator);
  state = singular;
  references sequence with type `NSt7__debug6vectorIP6CQuerySaIS2_EEE' @ 0x0x10fd960
}

Thread 1 "znc" received signal SIGABRT, Aborted.
0x00007ffff6126428 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:54
54      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory
```

**Comment by DarthGandalf** [comment]
this doesn't look like "bt full"

2017-03-13 16:52 GMT+00:00 MuffinMedic <notifications@github.com>:

**Comment by MuffinMedic** [comment]
```
Signal        Stop	Print	Pass to program	Description
SIGPIPE       No	No	Yes		Broken pipe
Starting program: /usr/local/bin/znc -D
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffecd86700 (LWP 10752)]

Thread 1 "znc" received signal SIGABRT, Aborted.
0x00007ffff6126428 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
Undefined command: "exit".  Try "help".
Not confirmed.
#0  0x00007ffff6126428 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:54
        resultvar = 0
        pid = 10748
        selftid = 10748
#1  0x00007ffff612802a in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {
            __val = {0, 45015380024, 140737325520192, 140737334406968, 36, 
              140737488348640, 0, 0, 140737322021064, 2, 140737322579709, 1, 
              140737325524848, 0, 140737354032960, 14}}, sa_flags = -1555318272, 
          sa_restorer = 0x7fffffffa3d0}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007ffff6cabf95 in __gnu_debug::_Error_formatter::_M_error() const ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#3  0x00007fffedf45b72 in __gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<CQuery* const*, std::__cxx1998::vector<CQuery*, std::allocator<CQuery*> > >, std::__debug::vector<CQuery*, std::allocator<CQuery*> > >::operator++ (this=0x7fffffffa680)
    at /usr/include/c++/5/debug/safe_iterator.h:329
No locals.
#4  0x00007fffedf43c31 in CClientAwayMod::OnUserRaw (this=0xbb38d0, sLine=...)
    at clientaway.cpp:155
        pQuery = 0x17ed5a0
        __for_range = std::__debug::vector of length 0, capacity 1
        __for_begin = 
        __for_end = 
        vChans = std::__debug::vector of length 173, capacity 256 = {0x1124540, 
          0x1124990, 0xba9e80, 0xba9840, 0xb88ce0, 0xb891d0, 0xb89670, 0xb89b10, 
          0xb89fb0, 0xb8a4e0, 0xb8a930, 0xb8add0, 0xb8b270, 0xb8b710, 0xb8bbb0, 
          0xb8c050, 0xb8c4f0, 0xb8caa0, 0xb8cf40, 0xb8d3e0, 0xb8d880, 0xb8dd20, 
          0xb8e1c0, 0xb8e660, 0xb8eb00, 0xb8efa0, 0xb8f440, 0xb8f8e0, 0xb8fd80, 
          0xb90220, 0xb906c0, 0xb90b60, 0xb91000, 0xb916b0, 0xb91b50, 0xb91ff0, 
          0xb92490, 0xb92930, 0xb92dd0, 0xb93270, 0xb93710, 0xb93bb0, 0xb94050, 
          0xb944f0, 0xb94990, 0xb94e30, 0xb952d0, 0xb95770, 0xb95c10, 0xb960b0, 
          0xb96550, 0xb969f0, 0xb96e90, 0xb97330, 0xb977d0, 0xb97c70, 0xb98110, 
          0xb985b0, 0xb98a50, 0xb98ef0, 0xb99390, 0xb99830, 0xb99cd0, 0xb9a170, 
          0xb9a610, 0x111a120, 0x111ba60, 0x111d130, 0xb9aec0, 0xb9b360, 0xb9b800, 
          0xb9bca0, 0xb9c140, 0xb9c5e0, 0xb9ca80, 0xb9cf20, 0xb9d3c0, 0xb9d860, 
          0xb9dd00, 0xb9e1a0, 0xb9e640, 0xb9eae0, 0xb9ef80, 0xb9f420, 0xb9f8c0, 
          0xb9fd60, 0xba0200, 0xba06a0, 0xba0b40, 0xba0fe0, 0xba1480, 0xba1920, 
          0xba1dc0, 0xba2260, 0xba2700, 0xba2ba0, 0xba3040, 0xba34e0, 0xba3980, 
          0xba3e20, 0xba42c0, 0xba4760, 0xba4c00, 0xba50a0, 0xba5540, 0xba59e0, 
          0xba5e80, 0xba6320, 0xba67c0, 0xba6c60, 0xba7100, 0xba75a0, 0xba7a40, 
          0xba7ee0, 0xba8380, 0xba8820, 0xba8cc0, 0xba9160, 0x1124de0, 0x1125040, 
          0x11252a0, 0x1125500, 0x1125760, 0x11259c0, 0x1125c20, 0x1125e80, 0x11260e0, 
          0x1126340, 0x11265a0, 0xb9aab0, 0x1127010, 0x1127270, 0x11274d0, 0x1127730, 
          0x1127990, 0x1127bf0, 0x1127e50, 0x11280b0, 0x1128310, 0x1128570, 0x11287d0, 
          128a30, 0x1128c90, 0x1128ef0, 0x1129150, 0x11293b0, 0x1129610, 0x1129870, 0x1129ad0, 0x1129d30, 0x1129f90, 0x112a1f0, 0x112a450, 0x112a6b0, 0x112a910, 0x112ab70, 0x112add0, 0x112b030, 
          0x112b290, 0x112b4f0, 0x112b750, 0x112b9b0, 0x112bc10, 0x112be70, 0x112c0d0, 0x112c330, 0x112c590, 0x112c7f0, 0x112ca50, 0x112ccb0, 0x112cf10, 0x112d170, 0x112d3d0}
        it = 
        sCmd = {<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >> = "AWAY", static CaseSensitive = CaseSensitivity::CaseSensitive, 
          static CaseInsensitive = CaseSensitivity::CaseInsensitive}
#5  0x00000000006ec000 in CModules::OnUserRaw (this=0xb7c240, sLine=...) at src/Modules.cpp:848
        pMod = 0xbb38d0
        e = CModule::CONTINUE
        pOldClient = 0x0
        pOldUser = 0x0
        pNetwork = 0x0
        a = 2
        bHaltCore = false
#6  0x00000000006bd4bf in CClient::ReadLine (this=0x33d9470, sData=...) at src/Client.cpp:111
        UMods = @0xb7c240: {<std::__debug::vector<CModule*, std::allocator<CModule*> >> = std::__debug::vector of length 15, capacity 16 = {0xbafb20, 0xbafe40, 0xbb38d0, 0x112eb00, 0x112f610, 
            0x1130e10, 0x11329f0, 0x1133e20, 0x11340d0, 0x11343b0, 0x1135b20, 0x1136290, 0x1135f90, 0x1137640, 0x1141d40}, m_pUser = 0x0, m_pNetwork = 0x10fd790, m_pClient = 0x33d9470}
        pOldUNetwork = 0x0
        pOldUClient = 0x0
        bGlobalExited = false
        bUserExited = false
        sLine = {<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >> = "AWAY", static CaseSensitive = CaseSensitivity::CaseSensitive, 
          static CaseInsensitive = CaseSensitivity::CaseInsensitive}
        bReturn = false
        sCommand = {<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >> = "ZNC", static CaseSensitive = CaseSensitivity::CaseSensitive, 
          static CaseInsensitive = CaseSensitivity::CaseInsensitive}
#7  0x00000000006152d2 in Csock::PushBuff (this=0x33d9470, data=0x3648370 "AWAY\r\n", len=6, bStartAtZero=false) at src/Csocket.cpp:2383
        sUTF8 = {<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >> = "AWAY\r\n", static CaseSensitive = CaseSensitivity::CaseSensitive, 
          static CaseInsensitive = CaseSensitivity::CaseInsensitive}
        sBuff = {<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >> = "AWAY\r\n", static CaseSensitive = CaseSensitivity::CaseSensitive, 
          static CaseInsensitive = CaseSensitivity::CaseInsensitive}
        iFind = 5
        iStartPos = 0
#8  0x0000000000618bb7 in CSocketManager::Loop (this=0xa7ea18) at src/Csocket.cpp:3456
        iLen = 4096
        cBuff = {m_pBuffer = 0x3648370 "AWAY\r\n"}
        bytes = 6
        pcSock = 0x33d9470
        iErrno = CSocketManager::SUCCESS
        itSock = {first = , second = CSocketManager::SUCCESS}
        mpeSocks = std::__debug::map with 1 elements = {[0x33d9470] = CSocketManager::SUCCESS}
        iMilliNow = 1489423691354
#9  0x0000000000618ff4 in CSocketManager::DynamicSelectLoop (this=0xa7ea18, iLowerBounds=100000, iUpperBounds=600000000, iMaxResolution=3600) at src/Csocket.cpp:3514
No locals.
#10 0x00000000006313bf in CZNC::Loop (this=0xa7e940) at src/znc.cpp:221
        sError = {<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >> = "", static CaseSensitive = CaseSensitivity::CaseSensitive, 
          static CaseInsensitive = CaseSensitivity::CaseInsensitive}
        eState = CZNC::ECONFIG_NOTHING
#11 0x00000000005f834b in main (argc=2, argv=0x7fffffffe5e8) at src/main.cpp:422
        sa = {__sigaction_handler = {sa_handler = 0x5f6f2c <die(int)>, sa_sigaction = 0x5f6f2c <die(int)>}, sa_mask = {__val = {0 <repeats 16 times>}}, sa_flags = -2147483648, 
          sa_restorer = 0x7a8270 <__libc_csu_init>}
        iRet = 0
        sConfig = {<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >> = "", static CaseSensitive = CaseSensitivity::CaseSensitive, 
          static CaseInsensitive = CaseSensitivity::CaseInsensitive}
        sDataDir = {<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >> = "", static CaseSensitive = CaseSensitivity::CaseSensitive, 
          static CaseInsensitive = CaseSensitivity::CaseInsensitive}
        iArg = -1
        iOptIndex = -1
        bMakeConf = false
        bMakePass = false
        bAllowRoot = false
        bForeground = true
        bMakePem = false
        pZNC = 0xa7e940
        sConfigError = {<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >> = "", static CaseSensitive = CaseSensitivity::CaseSensitive, 
          static CaseInsensitive = CaseSensitivity::CaseInsensitive}
#0  0x00007ffff6126428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
        resultvar = 0
        pid = 10748
        selftid = 10748
#1  0x00007ffff612802a in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {0, 45015380024, 140737325520192, 140737334406968, 36, 140737488348640, 0, 0, 140737322021064, 2, 
              140737322579709, 1, 140737325524848, 0, 140737354032960, 14}}, sa_flags = -1555318272, sa_restorer = 0x7fffffffa3d0}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007ffff6cabf95 in __gnu_debug::_Error_formatter::_M_error() const () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#3  0x00007fffedf45b72 in __gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<CQuery* const*, std::__cxx1998::vector<CQuery*, std::allocator<CQuery*> > >, std::__debug::vector<CQuery*, std::allocator<CQuery*> > >::operator++ (this=0x7fffffffa680) at /usr/include/c++/5/debug/safe_iterator.h:329
No locals.
#4  0x00007fffedf43c31 in CClientAwayMod::OnUserRaw (this=0xbb38d0, sLine=...) at clientaway.cpp:155
        pQuery = 0x17ed5a0
        __for_range = std::__debug::vector of length 0, capacity 1
        __for_begin = 
        __for_end = 
        vChans = std::__debug::vector of length 173, capacity 256 = {0x1124540, 0x1124990, 0xba9e80, 0xba9840, 0xb88ce0, 0xb891d0, 0xb89670, 0xb89b10, 0xb89fb0, 0xb8a4e0, 0xb8a930, 0xb8add0, 0xb8b270, 
          0xb8b710, 0xb8bbb0, 0xb8c050, 0xb8c4f0, 0xb8caa0, 0xb8cf40, 0xb8d3e0, 0xb8d880, 0xb8dd20, 0xb8e1c0, 0xb8e660, 0xb8eb00, 0xb8efa0, 0xb8f440, 0xb8f8e0, 0xb8fd80, 0xb90220, 0xb906c0, 0xb90b60, 
          0xb91000, 0xb916b0, 0xb91b50, 0xb91ff0, 0xb92490, 0xb92930, 0xb92dd0, 0xb93270, 0xb93710, 0xb93bb0, 0xb94050, 0xb944f0, 0xb94990, 0xb94e30, 0xb952d0, 0xb95770, 0xb95c10, 0xb960b0, 0xb96550, 
          0xb969f0, 0xb96e90, 0xb97330, 0xb977d0, 0xb97c70, 0xb98110, 0xb985b0, 0xb98a50, 0xb98ef0, 0xb99390, 0xb99830, 0xb99cd0, 0xb9a170, 0xb9a610, 0x111a120, 0x111ba60, 0x111d130, 0xb9aec0, 
          0xb9b360, 0xb9b800, 0xb9bca0, 0xb9c140, 0xb9c5e0, 0xb9ca80, 0xb9cf20, 0xb9d3c0, 0xb9d860, 0xb9dd00, 0xb9e1a0, 0xb9e640, 0xb9eae0, 0xb9ef80, 0xb9f420, 0xb9f8c0, 0xb9fd60, 0xba0200, 0xba06a0, 
          0xba0b40, 0xba0fe0, 0xba1480, 0xba1920, 0xba1dc0, 0xba2260, 0xba2700, 0xba2ba0, 0xba3040, 0xba34e0, 0xba3980, 0xba3e20, 0xba42c0, 0xba4760, 0xba4c00, 0xba50a0, 0xba5540, 0xba59e0, 0xba5e80, 
          0xba6320, 0xba67c0, 0xba6c60, 0xba7100, 0xba75a0, 0xba7a40, 0xba7ee0, 0xba8380, 0xba8820, 0xba8cc0, 0xba9160, 0x1124de0, 0x1125040, 0x11252a0, 0x1125500, 0x1125760, 0x11259c0, 0x1125c20, 
          0x1125e80, 0x11260e0, 0x1126340, 0x11265a0, 0xb9aab0, 0x1127010, 0x1127270, 0x11274d0, 0x1127730, 0x1127990, 0x1127bf0, 0x1127e50, 0x11280b0, 0x1128310, 0x1128570, 0x11287d0, 0x1128a30, 
          0x1128c90, 0x1128ef0, 0x1129150, 0x11293b0, 0x1129610, 0x1129870, 0x1129ad0, 0x1129d30, 0x1129f90, 0x112a1f0, 0x112a450, 0x112a6b0, 0x112a910, 0x112ab70, 0x112add0, 0x112b030, 0x112b290, 
          0x112b4f0, 0x112b750, 0x112b9b0, 0x112bc10, 0x112be70, 0x112c0d0, 0x112c330, 0x112c590, 0x112c7f0, 0x112ca50, 0x112ccb0, 0x112cf10, 0x112d170, 0x112d3d0}
        it = 
        sCmd = {<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >> = "AWAY", static CaseSensitive = CaseSensitivity::CaseSensitive, 
          static CaseInsensitive = CaseSensitivity::CaseInsensitive}
#5  0x00000000006ec000 in CModules::OnUserRaw (this=0xb7c240, sLine=...) at src/Modules.cpp:848
        pMod = 0xbb38d0
        e = CModule::CONTINUE
        pOldClient = 0x0
        pOldUser = 0x0
        pNetwork = 0x0
        a = 2
        bHaltCore = false
#6  0x00000000006bd4bf in CClient::ReadLine (this=0x33d9470, sData=...) at src/Client.cpp:111
        UMods = @0xb7c240: {<std::__debug::vector<CModule*, std::allocator<CModule*> >> = std::__debug::vector of length 15, capacity 16 = {0xbafb20, 0xbafe40, 0xbb38d0, 0x112eb00, 0x112f610, 
            0x1130e10, 0x11329f0, 0x1133e20, 0x11340d0, 0x11343b0, 0x1135b20, 0x1136290, 0x1135f90, 0x1137640, 0x1141d40}, m_pUser = 0x0, m_pNetwork = 0x10fd790, m_pClient = 0x33d9470}
        pOldUNetwork = 0x0
        pOldUClient = 0x0
        bGlobalExited = false
        bUserExited = false
        sLine = {<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >> = "AWAY", static CaseSensitive = CaseSensitivity::CaseSensitive, 
          static CaseInsensitive = CaseSensitivity::CaseInsensitive}
        bReturn = false
        sCommand = {<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >> = "ZNC", static CaseSensitive = CaseSensitivity::CaseSensitive, 
          static CaseInsensitive = CaseSensitivity::CaseInsensitive}
#7  0x00000000006152d2 in Csock::PushBuff (this=0x33d9470, data=0x3648370 "AWAY\r\n", len=6, bStartAtZero=false) at src/Csocket.cpp:2383
        sUTF8 = {<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >> = "AWAY\r\n", static CaseSensitive = CaseSensitivity::CaseSensitive, 
          static CaseInsensitive = CaseSensitivity::CaseInsensitive}
        sBuff = {<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >> = "AWAY\r\n", static CaseSensitive = CaseSensitivity::CaseSensitive, 
          static CaseInsensitive = CaseSensitivity::CaseInsensitive}
        iFind = 5
        iStartPos = 0
#8  0x0000000000618bb7 in CSocketManager::Loop (this=0xa7ea18) at src/Csocket.cpp:3456
        iLen = 4096
        cBuff = {m_pBuffer = 0x3648370 "AWAY\r\n"}
        bytes = 6
        pcSock = 0x33d9470
        iErrno = CSocketManager::SUCCESS
        itSock = {first = , second = CSocketManager::SUCCESS}
        mpeSocks = std::__debug::map with 1 elements = {[0x33d9470] = CSocketManager::SUCCESS}
        iMilliNow = 1489423691354
#9  0x0000000000618ff4 in CSocketManager::DynamicSelectLoop (this=0xa7ea18, iLowerBounds=100000, iUpperBounds=600000000, iMaxResolution=3600) at src/Csocket.cpp:3514
No locals.
#10 0x00000000006313bf in CZNC::Loop (this=0xa7e940) at src/znc.cpp:221
        sError = {<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >> = "", static CaseSensitive = CaseSensitivity::CaseSensitive, 
          static CaseInsensitive = CaseSensitivity::CaseInsensitive}
        eState = CZNC::ECONFIG_NOTHING
#11 0x00000000005f834b in main (argc=2, argv=0x7fffffffe5e8) at src/main.cpp:422
        sa = {__sigaction_handler = {sa_handler = 0x5f6f2c <die(int)>, sa_sigaction = 0x5f6f2c <die(int)>}, sa_mask = {__val = {0 <repeats 16 times>}}, sa_flags = -2147483648, 
          sa_restorer = 0x7a8270 <__libc_csu_init>}
        iRet = 0
        sConfig = {<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >> = "", static CaseSensitive = CaseSensitivity::CaseSensitive, 
          static CaseInsensitive = CaseSensitivity::CaseInsensitive}
        sDataDir = {<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >> = "", static CaseSensitive = CaseSensitivity::CaseSensitive, 
          static CaseInsensitive = CaseSensitivity::CaseInsensitive}
        iArg = -1
        iOptIndex = -1
        bMakeConf = false
        bMakePass = false
        bAllowRoot = false
        bForeground = true
        bMakePem = false
        pZNC = 0xa7e940
        sConfigError = {<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >> = "", static CaseSensitive = CaseSensitivity::CaseSensitive, 
          static CaseInsensitive = CaseSensitivity::CaseInsensitive}
```

**Comment by DarthGandalf** [comment]
As discussed with @kylef, it's a bug in the external [clientaway](http://wiki.znc.in/Clientaway) module, introduced in https://github.com/kylef/znc-contrib/pull/18

**Comment by kylef** [comment]
Should be fixed by https://github.com/kylef/znc-contrib/pull/22
