### ISSUE TITLE
Prototype error for CMessage.GetParamsColon on Python

### ISSUE THREAD

**Issue by worstje** [znc/znc#1749]
**Version**: 1.8.1

The API bindings appear unhappy in Python.

```
Traceback (most recent call last):
  File "/.../modules/blah.py", line 246, in OnPrivCTCPMessage
    self.PutModule("ParamsColon 1: " + str(message.GetParamsColon(1)))
  File "/.../znc/modpython/znc_core.py", line 3588, in GetParamsColon
     return _znc_core.CMessage_GetParamsColon(self, uIdx, uLen)
TypeError: Wrong number or type of arguments for overloaded function 'CMessage_GetParamsColon'.
  Possible C/C++ prototypes are:
    CMessage::GetParamsColon(unsigned int,unsigned int) const
    CMessage::GetParamsColon(unsigned int) const
```

Relevant lines in `/.../znc/modpython/znc_core.py` are as follows:

```
def GetParamsColon(self, uIdx: 'unsigned int', uLen: 'unsigned int'=-1) -> "CString":
    return _znc_core.CMessage_GetParamsColon(self, uIdx, uLen)
```

Clearly an unsigned int cannot be -1 (why that definition on C++ side anyways?!), so my guess is that some code (SWIG?) chokes on this.

I have tried setting `uLen` to None in the hope it would fall back to the 1-parameter version, but no dice.

Temporary workaround for anyone who needs the default for that parameter:

```
import _znc_core
self.PutModule("ParamsColon 1: " + str(_znc_core.CMessage_GetParamsColon(message, 1)))
```

I don't know what the proper way is to resolve this. Regenerate SWIG? Fix the original class definition with a proper overload somehow? I leave it up to the experts. 😄

**Comment by DarthGandalf** [comment]
Can you show your code?

**Comment by worstje** [comment]
It is pretty much in the traceback, which is why I didn't post it. It is just a global module, with the hook in it, and the line of the exception.

```python
    # virtual EModRet CModule::OnPrivCTCPMessage ( CCTCPMessage& Message )
    def OnPrivCTCPMessage(self, message):
        self.PutModule("ParamsColon 1: " + str(message.GetParamsColon(1)))
```
