### ISSUE TITLE
modpython broken in nightlies [$5]

### ISSUE THREAD

**Issue by md-5** [znc/znc#809]
````
<md_5> [2015-01-06 09:06:10.711558] Unable to load module [modpython] [Module [modpython] aborted: Traceback (most recent call last):\x0A  File "./modules/modpython/znc.py", line 23, in <module>\x0A    from znc_core import *\x0A  File "./modules/modpython/znc_core.py", line 3382\x0A    def CDir_MakeDir(sPath: 'CString', iMode: 'mode_t'=0700) -> "bool":\x0A                                                          ^\x0ASyntaxError: invalid token\x0A]
<md_5> trying to use python2 instead of python3 ?
<md_5> (znc-git-2015-01-05.tar.gz on Ubuntu 14.10)
<DarthGandalf> How does line 3382 of znc_cory.py look like?
<DarthGandalf> oh, nightly?
<md_5> def CDir_MakeDir(sPath: 'CString', iMode: 'mode_t'=0700) -> "bool":
<md_5> that is the line
<DarthGandalf> Oh...
<DarthGandalf> SWIG 3.0.3 :(
````

**Comment by DarthGandalf** [comment]
Dessa downgraded SWIG to 3.0.2
