### ISSUE TITLE
zsh: segmentation fault  znc --version

### ISSUE THREAD

**Issue by Mikaela** [znc/znc#838]
```gdb
Signal        Stop	Print	Pass to program	Description
SIGPIPE       No	Yes	Yes		Broken pipe
Starting program: /home/users/mikaela/.local/bin/znc --version
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00000000005fa8c0 in CZNC::GetTag (bIncludeVersion=true, bHTML=false) at ../src/znc.cpp:100
100		if (!Get().m_bHideVersion) {
#0  0x00000000005fa8c0 in CZNC::GetTag (bIncludeVersion=true, bHTML=false) at ../src/znc.cpp:100
        sAddress = {<std::basic_string<char, std::char_traits<char>, std::allocator<char> >> = {static npos = <optimized out>, 
            _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x3b6226234b0 ""}}, static CaseSensitive = CaseSensitive, 
          static CaseInsensitive = CaseInsensitive}
        sVersion = {<std::basic_string<char, std::char_traits<char>, std::allocator<char> >> = {static npos = <optimized out>, 
            _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
              _M_p = 0x10004157f1c0300 <Address 0x10004157f1c0300 out of bounds>}}, static CaseSensitive = CaseSensitive, static CaseInsensitive = CaseInsensitive}
#1  0x00000000005c4e54 in main (argc=2, argv=0x3b622623598) at ../src/main.cpp:209
        bMakeConf = false
        sConfigError = {<std::basic_string<char, std::char_traits<char>, std::allocator<char> >> = {static npos = <optimized out>, 
            _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x0}}, static CaseSensitive = CaseSensitive, 
          static CaseInsensitive = CaseInsensitive}
        sConfig = {<std::basic_string<char, std::char_traits<char>, std::allocator<char> >> = {static npos = <optimized out>, 
            _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0xa1a838 ""}}, static CaseSensitive = CaseSensitive, 
          static CaseInsensitive = CaseInsensitive}
        sDataDir = {<std::basic_string<char, std::char_traits<char>, std::allocator<char> >> = {static npos = <optimized out>, 
            _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0xa1a838 ""}}, static CaseSensitive = CaseSensitive, 
          static CaseInsensitive = CaseInsensitive}
        iArg = 118
        iOptIndex = 1
        bMakePem = false
        pZNC = 0x3ad720d3c48
        bMakePass = false
        bAllowRoot = false
        bForeground = false
#0  0x00000000005fa8c0 in CZNC::GetTag (bIncludeVersion=true, bHTML=false) at ../src/znc.cpp:100
        sAddress = {<std::basic_string<char, std::char_traits<char>, std::allocator<char> >> = {static npos = <optimized out>, 
            _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x3b6226234b0 ""}}, static CaseSensitive = CaseSensitive, 
          static CaseInsensitive = CaseInsensitive}
        sVersion = {<std::basic_string<char, std::char_traits<char>, std::allocator<char> >> = {static npos = <optimized out>, 
            _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
              _M_p = 0x10004157f1c0300 <Address 0x10004157f1c0300 out of bounds>}}, static CaseSensitive = CaseSensitive, static CaseInsensitive = CaseInsensitive}
#1  0x00000000005c4e54 in main (argc=2, argv=0x3b622623598) at ../src/main.cpp:209
        bMakeConf = false
        sConfigError = {<std::basic_string<char, std::char_traits<char>, std::allocator<char> >> = {static npos = <optimized out>, 
            _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x0}}, static CaseSensitive = CaseSensitive, 
          static CaseInsensitive = CaseInsensitive}
        sConfig = {<std::basic_string<char, std::char_traits<char>, std::allocator<char> >> = {static npos = <optimized out>, 
            _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0xa1a838 ""}}, static CaseSensitive = CaseSensitive, 
          static CaseInsensitive = CaseInsensitive}
        sDataDir = {<std::basic_string<char, std::char_traits<char>, std::allocator<char> >> = {static npos = <optimized out>, 
            _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0xa1a838 ""}}, static CaseSensitive = CaseSensitive, 
          static CaseInsensitive = CaseInsensitive}
        iArg = 118
        iOptIndex = 1
        bMakePem = false
        pZNC = 0x3ad720d3c48
        bMakePass = false
        bAllowRoot = false
        bForeground = false
A debugging session is active.

	Inferior 1 [process 9930] will be killed.

Quit anyway? (y or n) 
```

```
2015-02-01 17:35:27+0200 < *status> ZNC - 1.5.0-git-552-ff88f24 - http://znc.in
2015-02-01 17:35:27+0200 < *status> IPv6: yes, SSL: yes, DNS: threads, charset: yes
```
Debian GNU/Linux 7.8 (wheezy)

**Comment by Mikaela** [comment]
bt full added.
